name: AWS Infrastructure Provisioning

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        description: 'Working directory for OpenTofu'
        required: true
        type: string
      ENVIRONMENTS_CONFIG_DIR:
        description: 'Directory for environment configs'
        required: true
        type: string
      AWS_REGION:
        description: 'AWS region'
        required: true
        type: string
      CI_ENVIRONMENT_NAME:
        description: 'Environment name'
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        description: 'SSH private key for secure file access'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: OpenTofu Plan
    runs-on: ubuntu-22.04
    environment: ${{ inputs.CI_ENVIRONMENT_NAME }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget git curl python3 python3-pip jq unzip
          wget https://github.com/opentofu/opentofu/releases/download/v1.9.0/tofu_1.9.0_linux_amd64.zip
          unzip -o tofu_1.9.0_linux_amd64.zip
          sudo mv tofu /usr/local/bin/
          rm tofu_1.9.0_linux_amd64.zip
          pip3 install awscli
          export PATH=$PATH:/home/runner/.local/bin

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          eval $(ssh-agent -s)
          echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_NUMBER_ }}:role/${{ vars.SHARED_DEPLOYMENT_ROLE }}
          role-session-name: GitHubActions
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Set Environment Variables
        run: |
          echo "ACTUAL_ACCOUNT_NUMBER=${{ vars.AWS_ACCOUNT_NUMBER_ }}" >> $GITHUB_ENV
          echo "SHARED_DEPLOYMENT_ROLE=${{ vars.SHARED_DEPLOYMENT_ROLE }}" >> $GITHUB_ENV
          echo "TF_VAR_account_number=${{ vars.AWS_ACCOUNT_NUMBER_ }}" >> $GITHUB_ENV
          echo "Deploying in ${{ vars.AWS_ACCOUNT_NUMBER_ }} account with role ${{ vars.SHARED_DEPLOYMENT_ROLE }} for environment ${{ inputs.CI_ENVIRONMENT_NAME }}..."

      - name: Run OpenTofu Plan
        run: |
          cd "${{ inputs.WORKING_DIRECTORY }}"
          tofu init -input=false -backend-config="../${{ inputs.ENVIRONMENTS_CONFIG_DIR }}/ch/${{ inputs.AWS_REGION }}/${{ inputs.CI_ENVIRONMENT_NAME }}/backend.tfvars"
          tofu validate -no-color
          tofu plan -input=false -no-color -out=tfplan -var-file="../${{ inputs.ENVIRONMENTS_CONFIG_DIR }}/ch/${{ inputs.AWS_REGION }}/${{ inputs.CI_ENVIRONMENT_NAME }}/inputs.tfvars"
          echo "Generating plan summary..."
          PLAN_OUTPUT=$(tofu show -no-color ./tfplan)
          echo "#### OpenTofu Plan Summary" > summary.md
          echo "#### Plan Output:" >> summary.md
          echo "``````" >> summary.md
          echo "$PLAN_OUTPUT" >> summary.md
          echo "``````" >> summary.md
          echo "#### Generated by GitHub Actions" >> summary.md
          cat summary.md

      - name: Upload Plan Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plan-artifacts
          path: |
            ${{ inputs.WORKING_DIRECTORY }}/.terraform.lock.hcl
            ${{ inputs.WORKING_DIRECTORY }}/.terraform
            ${{ inputs.WORKING_DIRECTORY }}/tfplan
            ${{ inputs.WORKING_DIRECTORY }}/summary.md
          retention-days: 7

  apply:
    name: OpenTofu Apply
    runs-on: ubuntu-22.04
    environment: ${{ inputs.CI_ENVIRONMENT_NAME }}
    environment: ${{ inputs.CI_ENVIRONMENT_NAME }}
    needs: plan
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://github.com/opentofu/opentofu/releases/download/v1.9.0/tofu_1.9.0_linux_amd64.zip
          unzip -o tofu_1.9.0_linux_amd64.zip
          sudo mv tofu /usr/local/bin/
          rm tofu_1.9.0_linux_amd64.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_NUMBER_ }}:role/${{ vars.SHARED_DEPLOYMENT_ROLE }}
          role-session-name: GitHubActions
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Set Environment Variables
        run: |
          echo "ACTUAL_ACCOUNT_NUMBER=${{ vars.AWS_ACCOUNT_NUMBER_ }}" >> $GITHUB_ENV
          echo "SHARED_DEPLOYMENT_ROLE=${{ vars.SHARED_DEPLOYMENT_ROLE }}" >> $GITHUB_ENV
          echo "TF_VAR_account_number=${{ vars.AWS_ACCOUNT_NUMBER_ }}" >> $GITHUB_ENV
          echo "Deploying in ${{ vars.AWS_ACCOUNT_NUMBER_ }} account with role ${{ vars.SHARED_DEPLOYMENT_ROLE }} for environment ${{ inputs.CI_ENVIRONMENT_NAME }}..."

      - name: Download Plan Artifacts
        uses: actions/download-artifact@v4
        with:
          name: plan-artifacts
          path: ${{ inputs.WORKING_DIRECTORY }}

      - name: Apply OpenTofu Plan
        run: |
          cd "${{ inputs.WORKING_DIRECTORY }}"
          echo "Applying the OpenTofu plan..."
          tofu apply -input=false -no-color -auto-approve "./tfplan"